# Generated by Django 5.1 on 2024-08-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('fProgrammer', 'Frontend Programmer'), ('bProgrammer', 'Backend Programmer')], default='fProgrammer', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.CharField(choices=[('J', 'Junior'), ('M', 'Mid'), ('S', 'senior')], default='J', max_length=1),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(choices=[('base', '1000 $'), ('mid', '3000 $'), ('top', '5000 $')], default='base', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='time_type',
            field=models.CharField(choices=[('ftime', 'Full-time'), ('ptime', 'Part-time')], default='ftime', max_length=100),
        ),
    ]
