# Generated by Django 5.1 on 2024-08-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0002_job_category_job_location_job_position_job_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('fProgrammer', 'Frontend Programmer'), ('bProgrammer', 'Backend Programmer')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(choices=[('J', 'Junior'), ('M', 'Mid'), ('S', 'senior')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(choices=[('base', '1000 $'), ('mid', '3000 $'), ('top', '5000 $')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='time_type',
            field=models.CharField(choices=[('ftime', 'Full-time'), ('ptime', 'Part-time')], max_length=100),
        ),
    ]
