# Generated by Django 5.1 on 2024-08-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0003_alter_job_category_alter_job_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='name',
        ),
    ]
