# Generated by Django 5.1 on 2024-08-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0004_remove_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
