# Generated by Django 5.1 on 2024-08-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0005_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
