# Generated by Django 5.1 on 2024-08-18 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contractor_app', '0001_initial'),
        ('Job_app', '0008_remove_job_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Contractor_app.contractor'),
        ),
    ]
