# Generated by Django 5.1 on 2024-08-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0009_job_contractor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='name',
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(choices=[('base', '1000 - 3000 $'), ('mid', '3000 - 5000 $'), ('top', '5000 - 7000 $')], max_length=100),
        ),
    ]
