# Generated by Django 5.1 on 2024-08-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0010_remove_job_name_alter_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='job 1', max_length=100),
            preserve_default=False,
        ),
    ]
